import type { CatalogProduct } from '@/types/catalog';

const svg = (label: string, a: string, b: string) => {
  const xml = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 800"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient></defs><rect width="800" height="800" rx="80" fill="url(#g)"/><circle cx="630" cy="130" r="180" fill="rgba(255,255,255,.12)"/><circle cx="150" cy="700" r="240" fill="rgba(255,255,255,.08)"/><rect x="260" y="95" width="280" height="610" rx="48" fill="#0b1020" opacity=".95"/><rect x="278" y="115" width="244" height="570" rx="38" fill="#111827"/><circle cx="400" cy="152" r="10" fill="#94a3b8"/><text x="400" y="430" text-anchor="middle" font-family="Arial" font-size="42" font-weight="700" fill="#f8fafc">${label}</text></svg>`;
  return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(xml)}`;
};

const now = new Date().toISOString();
const img = (label: string, a: string, b: string) => [{ url: svg(label,a,b), isMain:true, sortOrder:0 }];

export const demoProducts: CatalogProduct[] = [
  { id:'p1', slug:'iphone-17-pro', nameFa:'آیفون ۱۷ پرو', nameEn:'iPhone 17 Pro', price:129_900_000, salePrice:124_900_000, stock:12, isActive:true, featured:true, isNew:true, isBestSeller:true, createdAt:now, brand:{id:'apple',nameFa:'اپل',nameEn:'Apple',slug:'apple'}, category:{id:'phones',nameFa:'گوشی موبایل',nameEn:'Smartphones',slug:'phones'}, images:img('17 PRO','#1d4ed8','#7c3aed'), variants:[{id:'p1-v1',label:'256GB / 8GB',storage:'256GB',ram:'8GB',price:129_900_000,salePrice:124_900_000,stock:8,isDefault:true},{id:'p1-v2',label:'512GB / 12GB',storage:'512GB',ram:'12GB',price:145_900_000,stock:4}], review:{rating:4.9,count:184}, specs:{'نمایشگر':'6.3″ OLED ProMotion','دوربین':'48MP Pro Camera','پردازنده':'A19 Pro','باتری':'نسل جدید با شارژ سریع'}, tags:['پرچمدار','5G','ProMotion'] },
  { id:'p2', slug:'galaxy-s26-ultra', nameFa:'گلکسی S26 اولترا', nameEn:'Galaxy S26 Ultra', price:114_900_000, salePrice:109_900_000, stock:18, isActive:true, featured:true, isNew:true, isBestSeller:true, createdAt:now, brand:{id:'samsung',nameFa:'سامسونگ',nameEn:'Samsung',slug:'samsung'}, category:{id:'phones',nameFa:'گوشی موبایل',nameEn:'Smartphones',slug:'phones'}, images:img('S26 ULTRA','#0f766e','#0f172a'), variants:[{id:'p2-v1',label:'256GB / 12GB',storage:'256GB',ram:'12GB',price:114_900_000,salePrice:109_900_000,stock:11,isDefault:true},{id:'p2-v2',label:'512GB / 16GB',storage:'512GB',ram:'16GB',price:131_900_000,stock:7}], review:{rating:4.8,count:231}, specs:{'نمایشگر':'6.9″ Dynamic AMOLED','دوربین':'200MP AI Camera','پردازنده':'Snapdragon Elite','باتری':'5000mAh'}, tags:['Ultra','AI','قلم'] },
  { id:'p3', slug:'pixel-10-pro-xl', nameFa:'پیکسل ۱۰ پرو XL', nameEn:'Pixel 10 Pro XL', price:98_900_000, salePrice:93_900_000, stock:7, isActive:true, featured:true, isNew:true, createdAt:now, brand:{id:'google',nameFa:'گوگل',nameEn:'Google',slug:'google'}, category:{id:'phones',nameFa:'گوشی موبایل',nameEn:'Smartphones',slug:'phones'}, images:img('PIXEL 10','#312e81','#0891b2'), variants:[{id:'p3-v1',label:'256GB / 16GB',storage:'256GB',ram:'16GB',price:98_900_000,salePrice:93_900_000,stock:7,isDefault:true}], review:{rating:4.7,count:96}, specs:{'نمایشگر':'6.8″ LTPO OLED','دوربین':'Tensor AI Camera','پردازنده':'Tensor G5','باتری':'5050mAh'}, tags:['Android Pure','AI'] },
  { id:'p4', slug:'xiaomi-15-ultra', nameFa:'شیائومی ۱۵ اولترا', nameEn:'Xiaomi 15 Ultra', price:79_900_000, salePrice:74_900_000, stock:4, isActive:true, featured:false, isNew:false, isBestSeller:true, createdAt:now, brand:{id:'xiaomi',nameFa:'شیائومی',nameEn:'Xiaomi',slug:'xiaomi'}, category:{id:'phones',nameFa:'گوشی موبایل',nameEn:'Smartphones',slug:'phones'}, images:img('XIAOMI 15','#111827','#dc2626'), variants:[{id:'p4-v1',label:'512GB / 16GB',storage:'512GB',ram:'16GB',price:79_900_000,salePrice:74_900_000,stock:4,isDefault:true}], review:{rating:4.6,count:88}, specs:{'نمایشگر':'6.73″ AMOLED','دوربین':'Leica 1-inch','پردازنده':'Snapdragon 8 Elite','باتری':'5410mAh'}, tags:['Leica','Performance'] },
  { id:'p5', slug:'oneplus-13', nameFa:'وان‌پلاس ۱۳', nameEn:'OnePlus 13', price:67_900_000, salePrice:64_900_000, stock:0, isActive:true, featured:false, isNew:false, isBestSeller:false, createdAt:now, brand:{id:'oneplus',nameFa:'وان‌پلاس',nameEn:'OnePlus',slug:'oneplus'}, category:{id:'phones',nameFa:'گوشی موبایل',nameEn:'Smartphones',slug:'phones'}, images:img('ONEPLUS 13','#be123c','#fb7185'), variants:[], review:{rating:4.5,count:61}, specs:{'نمایشگر':'6.82″ AMOLED','پردازنده':'Snapdragon 8 Elite','باتری':'6000mAh'}, tags:['Fast','120Hz'] },
  { id:'p6', slug:'sony-xperia-1-vii', nameFa:'اکسپریا ۱ VII', nameEn:'Xperia 1 VII', price:91_900_000, stock:9, isActive:true, featured:false, isNew:true, isBestSeller:false, createdAt:now, brand:{id:'sony',nameFa:'سونی',nameEn:'Sony',slug:'sony'}, category:{id:'phones',nameFa:'گوشی موبایل',nameEn:'Smartphones',slug:'phones'}, images:img('XPERIA VII','#334155','#020617'), variants:[], review:{rating:4.3,count:43}, specs:{'نمایشگر':'4K OLED','دوربین':'Pro Camera','صدا':'Hi-Res Audio'}, tags:['Cinema','Audio'] },
  { id:'p7', slug:'airpods-pro-3', nameFa:'ایرپادز پرو ۳', nameEn:'AirPods Pro 3', price:18_900_000, salePrice:16_900_000, stock:21, isActive:true, featured:true, isNew:true, isBestSeller:true, createdAt:now, brand:{id:'apple',nameFa:'اپل',nameEn:'Apple',slug:'apple'}, category:{id:'audio',nameFa:'صوتی',nameEn:'Audio',slug:'audio'}, images:img('AIRPODS PRO','#475569','#e2e8f0'), variants:[{id:'p7-v1',label:'USB-C',price:18_900_000,salePrice:16_900_000,stock:21,isDefault:true}], review:{rating:4.8,count:317}, specs:{'قابلیت':'ANC نسل جدید','اتصال':'Bluetooth 5.4','باتری':'بهبود‌یافته'}, tags:['ANC','Spatial Audio'] },
  { id:'p8', slug:'galaxy-watch-8-classic', nameFa:'گلکسی واچ ۸ کلاسیک', nameEn:'Galaxy Watch 8 Classic', price:24_900_000, salePrice:22_900_000, stock:14, isActive:true, featured:true, isNew:true, isBestSeller:false, createdAt:now, brand:{id:'samsung',nameFa:'سامسونگ',nameEn:'Samsung',slug:'samsung'}, category:{id:'wearables',nameFa:'پوشیدنی',nameEn:'Wearables',slug:'wearables'}, images:img('WATCH 8','#1f2937','#94a3b8'), variants:[], review:{rating:4.5,count:109}, specs:{'نمایشگر':'Super AMOLED','مقاومت':'5ATM + IP68','GPS':'Dual-band'}, tags:['Health','GPS'] },
  { id:'p9', slug:'anker-prime-25000', nameFa:'پاوربانک Anker Prime 25000', nameEn:'Anker Prime 25000', price:9_900_000, salePrice:8_490_000, stock:31, isActive:true, featured:false, isNew:false, isBestSeller:true, createdAt:now, brand:{id:'anker',nameFa:'انکر',nameEn:'Anker',slug:'anker'}, category:{id:'accessories',nameFa:'لوازم جانبی',nameEn:'Accessories',slug:'accessories'}, images:img('ANKER 25K','#0f172a','#2563eb'), variants:[], review:{rating:4.7,count:142}, specs:{'ظرفیت':'25000mAh','خروجی':'165W','پورت':'USB-C'}, tags:['165W','Power Bank'] },
  { id:'p10', slug:'apple-20w-usb-c', nameFa:'آداپتور Apple 20W USB-C', nameEn:'Apple 20W USB-C Adapter', price:3_290_000, stock:50, isActive:true, featured:false, isNew:false, isBestSeller:true, createdAt:now, brand:{id:'apple',nameFa:'اپل',nameEn:'Apple',slug:'apple'}, category:{id:'accessories',nameFa:'لوازم جانبی',nameEn:'Accessories',slug:'accessories'}, images:img('20W','#f8fafc','#cbd5e1'), variants:[], review:{rating:4.6,count:211}, specs:{'توان':'20W','پورت':'USB-C PD'}, tags:['Original'] },
  { id:'p11', slug:'logitech-mx-master-4', nameFa:'ماوس Logitech MX Master 4', nameEn:'Logitech MX Master 4', price:12_900_000, salePrice:11_900_000, stock:16, isActive:true, featured:false, isNew:true, isBestSeller:false, createdAt:now, brand:{id:'logitech',nameFa:'لاجیتک',nameEn:'Logitech',slug:'logitech'}, category:{id:'accessories',nameFa:'لوازم جانبی',nameEn:'Accessories',slug:'accessories'}, images:img('MX MASTER','#1e293b','#7c3aed'), variants:[], review:{rating:4.4,count:72}, specs:{'اتصال':'Multi-device','حسگر':'8K DPI'}, tags:['Productivity'] },
  { id:'p12', slug:'kindle-colorsoft', nameFa:'کیندل Colorsoft', nameEn:'Kindle Colorsoft', price:31_900_000, stock:6, isActive:true, featured:true, isNew:true, isBestSeller:false, createdAt:now, brand:{id:'amazon',nameFa:'آمازون',nameEn:'Amazon',slug:'amazon'}, category:{id:'tablets',nameFa:'تبلت و مطالعه',nameEn:'Tablets & Reading',slug:'tablets'}, images:img('COLORSOFT','#0f766e','#f59e0b'), variants:[], review:{rating:4.6,count:49}, specs:{'نمایشگر':'7″ Color E-Ink','حافظه':'32GB','ضدآب':'IPX8'}, tags:['E-Ink','Reading'] },
];
