import { useEffect, useState } from 'react';
import { CalendarDays, Download, TrendingUp } from 'lucide-react';
import { AdminShell } from '@/components/admin/AdminShell';
import { AdminRevenueChart, AdminBars } from '@/components/admin/AdminChart';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { getDashboardData } from '@/services/admin/admin.service';
import type { AdminDashboardData } from '@/types/admin';
import { formatToman } from '@/lib/format/number';

export function AdminAnalyticsPage(){const [data,setData]=useState<AdminDashboardData|null>(null);const [error,setError]=useState('');useEffect(()=>{getDashboardData().then(setData).catch(e=>setError(e instanceof Error?e.message:'خطا در تحلیل'))},[]);return <AdminShell title="تحلیل و گزارش"><div className="mx-admin-stack">{error&&<div className="mx-admin-error">{error}</div>}{data&&<><div className="mx-admin-report-head"><div><div className="mx-kicker">ANALYTICS</div><h2>مرکز تحلیل Mobilex</h2><p>تصویر عملیاتی ۱۴ روز اخیر برای تصمیم‌گیری روزانه.</p></div><div className="mx-admin-actions"><Button variant="secondary" size="sm" icon={<CalendarDays size={13}/>}>۱۴ روز اخیر</Button><Button variant="primary" size="sm" icon={<Download size={13}/>}>خروجی گزارش</Button></div></div><div className="mx-admin-grid"><Card><div className="mx-report-label">درآمد کل</div><strong className="mx-report-value">{formatToman(data.revenue.reduce((s,x)=>s+x.revenue,0),'fa')}</strong></Card><Card><div className="mx-report-label">تعداد سفارش</div><strong className="mx-report-value">{data.revenue.reduce((s,x)=>s+x.orders,0).toLocaleString('fa-IR')}</strong></Card><Card><div className="mx-report-label">میانگین سفارش</div><strong className="mx-report-value">{formatToman((data.revenue.reduce((s,x)=>s+x.revenue,0))/(Math.max(1,data.revenue.reduce((s,x)=>s+x.orders,0))),'fa')}</strong></Card><Card><div className="mx-report-label">روند فروش</div><strong className="mx-report-value mx-report-positive">+ رشد داده‌شده</strong></Card></div><section className="mx-admin-panel"><div className="mx-admin-panel-head"><div><h2><TrendingUp size={14}/> عملکرد درآمد</h2><p>فروش روزانه و حجم سفارش</p></div></div><AdminRevenueChart data={data.revenue}/></section><div className="mx-admin-layout"><section className="mx-admin-panel"><div className="mx-admin-panel-head"><div><h2>محصولات برتر</h2><p>از نظر ارزش فروش</p></div></div><AdminBars items={data.topProducts.map(x=>({label:x.name,value:x.revenue}))}/></section><section className="mx-admin-panel"><div className="mx-admin-panel-head"><div><h2>وضعیت سفارش‌ها</h2><p>مقایسه تعداد سفارش</p></div></div><AdminBars items={data.ordersByStatus.map(x=>({label:x.status,value:x.count}))}/></section></div></>}</div></AdminShell>}
